version: '3.9'
services:
  mysql_db:
    image: mysql
    ports:
      - '3306:3306'
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secretpass
      MYSQL_DATABASE: spring_boot_with_llm
    restart: always
    networks:
      - spring_boot_with_llm_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8989:80'
    environment:
      PMA_HOST: mysql_db
      PMA_PORT: 3306
    depends_on:
      - mysql_db

  # ollama:
  #   image: ollama/ollama:0.3.9
  #   ports:
  #     - 11434:11434
  #   container_name: ollama
  #   pull_policy: always
  #   tty: true
  #   restart: always
  #   volumes:
  #     - ./install-ollama-models.sh:/install-ollama-models.sh
  #   entrypoint: ['/usr/bin/bash', '/install-ollama-models.sh']
  #   environment:
  #     - OLLAMA_KEEP_ALIVE=24h
  #     - OLLAMA_HOST=0.0.0.0
  #   networks:
  #     - spring_boot_with_llm_network

  # ollama-webui:
  #   image: ghcr.io/open-webui/open-webui:main
  #   container_name: ollama-webui
  #   depends_on:
  #     - ollama
  #   ports:
  #     - 8081:8080
  #   environment: # https://docs.openwebui.com/getting-started/env-configuration#default_models
  #     - OLLAMA_BASE_URLS=http://ollama:11434 #comma separated ollama hosts
  #     - ENV=dev
  #     - WEBUI_AUTH=False
  #     - WEBUI_URL=http://localhost:8081
  #     - WEBUI_SECRET_KEY=t0p-s3cr3t
  #   extra_hosts:
  #     - host.docker.internal:host-gateway
  #   restart: unless-stopped
  #   networks:
  #     - spring_boot_with_llm_network

  # qdrant:
  #   container_name: qdrant_demo_qdrant
  #   image: qdrant/qdrant:v1.11.3
  #   ports:
  #     - '6333:6333'
  #     - '6334:6334'

networks:
  spring_boot_with_llm_network:
    driver: bridge
